### PR TITLE
Support data source health check endpoint introduced with Grafana 9

### PR DESCRIPTION
**Pull request by amotl**
@jangaraj mentioned at https://github.com/panodata/grafana-client/issues/20#issuecomment-1160385363, that Grafana 9 features a dedicated data source health check endpoint [^1]. This patch implements the corresponding client support.

[^1]: https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#check-data-source-health

### CODE REVIEW

**Comment by amotl** [comment]
### Report

When running the example, I am receiving this outcome.

```log
$ python examples/datasource-health.py --type=prometheus --url=http://host.docker.internal:9090
2022-06-20 15:39:20,230 [urllib3.connectionpool             ] DEBUG  : Starting new HTTP connection (1): localhost:3000
2022-06-20 15:39:20,233 [urllib3.connectionpool             ] DEBUG  : http://localhost:3000 "GET /api/health HTTP/1.1" 200 70
2022-06-20 15:39:20,233 [__main__                           ] INFO   : Connected to Grafana version 9.0.0 at http://localhost:3000
2022-06-20 15:39:20,234 [__main__                           ] INFO   : Creating data source 'probe-prometheus'
2022-06-20 15:39:20,248 [urllib3.connectionpool             ] DEBUG  : http://localhost:3000 "POST /api/datasources HTTP/1.1" 409 104
2022-06-20 15:39:20,248 [__main__                           ] INFO   : Data source already exists: {'message': 'data source with the same name already exists', 'traceID': '00000000000000000000000000000000'}. Updating.
2022-06-20 15:39:20,262 [urllib3.connectionpool             ] DEBUG  : http://localhost:3000 "GET /api/datasources/name/probe-prometheus HTTP/1.1" 200 326
2022-06-20 15:39:20,294 [urllib3.connectionpool             ] DEBUG  : http://localhost:3000 "PUT /api/datasources/4 HTTP/1.1" 200 405
2022-06-20 15:39:20,310 [urllib3.connectionpool             ] DEBUG  : http://localhost:3000 "GET /api/datasources/4 HTTP/1.1" 200 326
2022-06-20 15:39:20,326 [urllib3.connectionpool             ] DEBUG  : http://localhost:3000 "GET /api/datasources/uid/NJoLtZq7k/health HTTP/1.1" 404 68
2022-06-20 15:39:20,327 [__main__                           ] ERROR  : Data source health check for uid=NJoLtZq7k failed: Client Error 404: Not found. Response: {'message': 'Not found', 'traceID': '00000000000000000000000000000000'}
```

```python
Traceback (most recent call last):
  File "/Users/amo/dev/panodata/sources/grafana-client/examples/datasource-health.py", line 159, in <module>
    run_healthcheck(grafana_client, grafana_version=grafana_version)
  File "/Users/amo/dev/panodata/sources/grafana-client/examples/datasource-health.py", line 135, in run_healthcheck
    health_info = health_inquiry(grafana, datasource, grafana_version=grafana_version)
  File "/Users/amo/dev/panodata/sources/grafana-client/examples/datasource-health.py", line 82, in health_inquiry
    health = grafana.datasource.health(datasource_uid=datasource_uid)
  File "/Users/amo/dev/panodata/sources/grafana-client/grafana_client/elements/datasource.py", line 31, in health
    r = self.client.GET(path)
  File "/Users/amo/dev/panodata/sources/grafana-client/grafana_client/client.py", line 131, in __request_runnner
    raise GrafanaClientError(
grafana_client.client.GrafanaClientError: Client Error 404: Not found
```

### Evaluation
`http://localhost:3000/api/datasources/uid/NJoLtZq7k/health` looks sane, requesting `http://localhost:3000/api/datasources/uid` actually works.

Through this log message, I am sure that I am on Grafana 9, running locally through Docker. The version string is inquired from the instance.
```
INFO   : Connected to Grafana version 9.0.0 at http://localhost:3000
```

### Thoughts
Am I missing something on this matter? Would this endpoint need to be explicitly enabled in the configuration? Is it enterprise only?

**Comment by jangaraj** [comment]
I would say doc is not correct - https://github.com/grafana/grafana/commit/6bb843bd0e747357c7563bdea77e8d01941c1601#diff-5e6dbad9a85fb156660edecabd16951c3ebbf9f026c063a6504a79b82fbdaccfR607 - it looks like `GET /api/datasources/:datasourceId/health` was introduced and also deprecated at the same time. Anyway, Grafana starts to use `uid`s everywhere, so `GET /api/datasources/uid/:uid/health` seems to be better API.

**Comment by amotl** [comment]
Thanks for your response. What is implemented right now is the `/uid/:uid/health` route, which responds with `404 Not Found`. I also tried the `/:datasourceId/health` route, but the result was the same.

**Comment by amotl** [comment]
I've just confirmed the behavior also with the current `main` image, like
```console
export GRAFANA_VERSION=main

docker run --rm -it \
    --publish=3000:3000 \
    --env='GF_SECURITY_ADMIN_PASSWORD=admin' \
    grafana/grafana:${GRAFANA_VERSION}
```

Do those endpoints actually work on your end, @jangaraj?

**Comment by jangaraj** [comment]
Nope, but I'm trying to figure out how to configure that. It works here - https://play.grafana.org/api/datasources/uid/000000098/health

**Comment by amotl** [comment]
I also thought about checking play.grafana.org, thank you for making a start. From a few samples I made, the outcome is 50/50.

### 200 OK
- Cloudwatch: https://play.grafana.org/api/datasources/uid/000000098/health
- TwinMaker: https://play.grafana.org/api/datasources/uid/qenjJQtnk/health

### 404 Not Found
- Testdata: https://play.grafana.org/api/datasources/uid/000000051/health
- Prometheus: https://play.grafana.org/api/datasources/uid/000000008/health

**Pull request merged**
